"""add hashed_password to customer

Revision ID: 814b34733684
Revises: d9f810d53fe8
Create Date: 2026-06-21 20:43:25.605837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814b34733684'
down_revision: Union[str, None] = 'd9f810d53fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('customers', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('customers', 'hashed_password')
    # ### end Alembic commands ###
